name: pictapp
description: This application was created as a final task for the "practical ICT" class.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  crypto: ^3.0.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.gif
  fonts:
    - family: M_PLUS_Rounded_1c
      fonts:
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
        weight: 900
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
        weight: 700
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
        weight: 500
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
        weight: 400
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
        weight: 300
      - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
        weight: 100
